### ISSUE TITLE
Microsoft.AspNetCore.Razor.Language v3.0.0 breaks this

### ISSUE THREAD

**Issue by wmcainsh** [SiliconOrchid/RoslynRazorTemplating#1]
Not an issue as such, just a heads up that upgrading the Microsoft.AspNetCore.Razor.Language NuGet package to v3.0.0 will break this.

**Comment by SiliconOrchid** [comment]
Hi William. Issue acknowledged (and thanks for taking the time to comment.)

Nuget backward compatibility is something I've been coming up against quite a few times - and it's a bit frustrating.  (For example, unrelated issue, but just last week, I was in contact with an author of a book, over a similar problem).

I am not currently maintaining this project actively, but as a response to your issue, I have updated both the blog (https://blogs.siliconorchid.com/post/coding-inspiration/razor-templating-with-roslyn/) and Git readme.md, with a message hopefully making it clear to use the package versions specified in the project.
