### ISSUE TITLE
Dynamic Html Element Attribute throws error

### ISSUE THREAD

**Issue by wmcainsh** [SiliconOrchid/RoslynRazorTemplating#2]
I know you aren't maintaining this but wondering if you have come across this before.

If you try to add content to an html element attribute from the model, it throws an error.

    <a href='@Model.Link1'>Google</a>

Results in:

_error CS0103: The name 'BeginWriteAttribute' does not exist in the current context_
_error CS0103: The name 'WriteAttributeValue' does not exist in the current context_
_error CS0103: The name 'EndWriteAttribute' does not exist in the current context_

I think I may be missing a MetadataReference but none of the ones I have tried have made any difference.

**Comment by SiliconOrchid** [comment]
Acknowledging that I could replicate the problem.   

I think I have fixed this (but I rushed it have not tested it much!)

Within  `RazorEngineBaseTemplate.cs` there are a methods for rendering the markup.  When your example attempted to write an **html attribute**, the engine was attempting to call methods specific to rendering attributes - but they had not been implemented (hence the fail).

I've now create the additional methods, necessary to  get things moving again.  See change https://github.com/SiliconOrchid/RoslynRazorTemplating/commit/9aca102181fbd4996491b4a62a9601457ebb4c76

These MS Docs are relevant:
 
* [RazorPage.BeginWriteAttribute](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.razor.razorpage.beginwriteattribute?view=aspnetcore-1.1), 

* [RazorPage.WriteAttributeValue](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.razor.razorpage.writeattributevalue?view=aspnetcore-1.1)

* [RazorPage.EndWriteAttribute](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.razor.razorpage.endwriteattribute?view=aspnetcore-1.1)

There are a swathe of other methods in the docs - I'm not sure which of these are entirely necessary, but it may be that this will need to be re-visited again in the future.

I think you should be good for now!

**Comment by wmcainsh** [comment]
Thanks. That's done the trick, missed it completely. The docs are pretty concise..
